 try~catch ~ finally

 - 오류 발생 시 중단되지 않고 지속됨
 - 예외 처리 시에 필요한 구문


<형식>

 try{
  //로직
 }catch(e){
  //에러발생시 로직
 }finally{
  //마지막
 }


 try: 에러발생시 원상복구 시도하는 곳
 catch : 에러 발생 시 코드 실행 흐름이 try에서 catch로 감.
       : 에러 정보 담고 있음
finally : 무조건 실행되는 코드. try종료되면 실행


try~finally 
에러발생하지 않은 경우 사용

try~catch~finally
에러 발생한 경우 사용
